# Site settings
title: Patrick Kelly
email: patomation@gmail.com
url: https://patomation.github.io
phone: '+66 80 626 2530'

keywords: "fullstack, full stack, developer, js, javascript, design, nodejs, node, npm, python, css, sass, less, saas, bootstarp, angular"
skills: "Design - Translation - Copy Wrighting- Web Consulting"
description: "Patrick Kelly is a designer and full stack developer with over 5 years experience."

meta_author: Kelly Patrick

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "073642"
  primary-rgb: "176,163,83" #"128,179,255"
  secondary: "859900" #"839496"
  secondary-dark: "2aa198"
  body-background-color: "002b36"
  body-color: "eee8d5"

# Footer settings
footer:
  copyright: Patrick Kelly
  location: Portland, OR
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/patomation
  - title: facebook
    url: https://www.facebook.com/patricknolankelly
  - title: stack-overflow
    url: https://stackoverflow.com/users/3179399/pat-o-mation
  - title: bitbucket
    url: http://bitbucket.org/patomation
  - title: github
    url: http://github.com/patomation
  - title: linkedin
    url: https://www.linkedin.com/in/patomation/
  - title: soundcloud
    url: https://soundcloud.com/advolkit

# Postal address (add as many lines as necessary)
address:
  - line: Portland, OR 97206

# Credits content
credits: 'Do it!'

# Build settings
markdown: kramdown
# permalink: pretty
permalink: /:title/
