# Site settings
title: Patrick Kelly
logo: awesome
email: patomation@gmail.com
url: https://patomation.github.io
phone: '+66 80 626 2530'

keywords: "fullstack, full stack, developer, js, javascript, design, nodejs, node, npm, python, css, sass, less, saas, bootstarp, angular"
skills: "Design - Translation - Copy Wrighting- Web Consulting"
description: "Patrick Kelly is a designer and full stack developer with over 5 years experience."

meta_author: Kelly Patrick



plugins:
  - jekyll-remote-theme

theme: minima
# remote-theme: patomation/simple-jekyll-theme


# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/patomation
  - title: facebook
    url: https://www.facebook.com/patricknolankelly
  - title: stack-overflow
    url: https://stackoverflow.com/users/3179399/pat-o-mation
  - title: bitbucket
    url: http://bitbucket.org/patomation
  - title: github
    url: http://github.com/patomation
  - title: linkedin
    url: https://www.linkedin.com/in/patomation/
  - title: soundcloud
    url: https://soundcloud.com/advolkit



# Build settings
markdown: kramdown
# permalink: pretty
permalink: /:title/


# --------------------------------------------------------
# SITE CONFIG
# --------------------------------------------------------

# Navigation
nav:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

#Footer Content
footer:  Copyright © your-name 2019
