brand: Patrick Kelly
title: Patrick Kelly
email: patomation@gmail.com
description: >-
  Self taught web designer who loves to travel and drink coffee.
  Camping enthusiast and mechanic. Lover of dogs.
profile-image: assets/images/Patrick-Profile-Picture-1.png
baseurl: "" # the subpath of your site, e.g. /blog
url: https://patomation.github.io
phone: '+66 80 626 2530'

keywords: "fullstack, full stack, developer, js, javascript, design, nodejs, node, npm, python, css, sass, less, saas, bootstarp, angular"
skills: "Design - Translation - Copy Wrighting- Web Consulting"

meta_author: Kelly Patrick

twitter_username:
github_username:

# Build settings
markdown: kramdown
# theme: minima

remote_theme: patomation/simple-jekyll-theme@0.1.5

google_anylitics: UA-70015022-1

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# Navigation
nav:
  - title: Projects
    url: /#projects
  - title: Contact
    url: /#contact
  # - title: Blog
  #   url: /blog/
  # - title: Contact
  #   url: /contact/
  # - title: About
  #   url: /about/

#Footer Content
footer:  Copyright © Patrick Kelly 2019

permalink: /:categories/:title:output_ext
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
