brand: patOmation
title: Patrick Kelly
author: Patrick Kelly
email: patomation@gmail.com
description: >-
  Self taught web designer who loves to travel and drink coffee.
  Camping enthusiast and mechanic. Lover of dogs.
profile-image: assets/images/Patrick-Profile-Picture-1.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

google_analytics:



# Build settings
markdown: kramdown
theme: simple-jekyll-theme

# --------------------------------------------------------
# SITE CONFIG
# --------------------------------------------------------

# Navigation
nav:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/




# Footer Content
footer:  Copyright © your-name 2019






plugins:
  - jekyll-feed
  - jekyll-seo-tag
